--1. Who is the senior most employee based on job title? 

Select * from employee order by levels desc limit 1;

--2. Which countries have the most Invoices?

Select billing_country, count(*) as total_invoices from invoice group by billing_country
order by total_invoices desc;

--3. What are top 3 values of total invoice?

Select total from invoice order by total desc limit 3;

--4. Which city has the best customers? We would like to throw a promotional Music
--Festival in the city we made the most money. Write a query that returns one city that
--has the highest sum of invoice totals. Return both the city name & sum of all invoice totals

Select billing_city, sum(total) as invoice_totals from invoice
group by billing_city order by invoice_totals desc limit 1;


--5. Who is the best customer? The customer who has spent the most money will be
--declared the best customer. Write a query that returns the person who has spent the
--most money


Select c.customer_id, c.first_name, c.last_name, sum(i.total) as total_spent from customer c join 
invoice i on c.customer_id = i.customer_id group by c.customer_id, c.first_name,
c.last_name order by total_spent desc limit 1;

--6. Find the music genre that has the highest number of tracks sold.

Select g.name, count(i.track_id) as total_tracks_sold from genre g join track t 
on g.genre_id = t.track_id join invoice_line i on t.track_id = i.track_id 
group by g.name order by total_tracks_sold desc;

--7. Write query to return the email, first name, last name, & Genre of all Rock Music
--listeners. Return your list ordered alphabetically by email starting with A

Select distinct c.email, c.first_name, c.last_name, g.name from customer c join invoice i 
on c.customer_id = i.customer_id join invoice_line il on i.invoice_id = il.invoice_id
join track t on il.track_id = t.track_id join genre g on t.genre_id = g.genre_id
where g.name like 'Rock' order by c.email;

--8. Let's invite the artists who have written the most rock music in our dataset. Write a
--query that returns the Artist name and total track count of the top 10 rock bands


Select a.artist_id, a.name, g.name, count(a.artist_id) as total_rock_music from artist a
join album al on a.artist_id = al.artist_id join track t on al.album_id = t.album_id
join genre g on t.genre_id = g.genre_id where g.name like 'Rock' group by a.artist_id, 
a.name, g.name order by total_rock_music desc limit 10;

--9. Return all the track names that have a song length longer than the average song length.
--Return the Name and Milliseconds for each track. Order by the song length with the
--longest songs listed first

Select name, milliseconds from track 
where milliseconds > (select avg(milliseconds) from track) order by milliseconds desc;

--10. Return the longest track for every genre.

Select * from (Select g.name as genre_name, t.name as track_name, t.milliseconds as track_length, 
dense_rank() over(partition by g.name order by milliseconds desc) 
as rank_no from genre g join track t on g.genre_id = t.genre_id) where rank_no = 1;

--11. Find customers who never bought any jazz genre tracks.


Select c.first_name, c.last_name from customer c where c.customer_id not in
(Select distinct c.customer_id from customer c left join invoice i 
on c.customer_id = i.customer_id left join invoice_line il on i.invoice_id = il.invoice_id
left join track t on il.track_id = t.track_id left join genre g on t.genre_id = g.genre_id
where g.name like 'Jazz');

--12. Find total revenue generated each month.

Select extract(year from invoice_date) as years, extract(month from invoice_date) as months, sum(total) as total_revenue
from invoice group by years, months order by years, months;

--13 Find how many invoices were generated each year.

Select extract(year from invoice_date) as years, count(invoice_id) as total_invoice
from invoice group by years order by years;

--14 Find the genre that contains the highest number of tracks.

Select g.name, count(t.name) as total_no_of_tracks from genre g join track t
on g.genre_id = t.genre_id group by g.name order by total_no_of_tracks desc;

--15 Return number of customers from each country.

Select country, count(*) as total_customer from customer group by country;

--16 Find total revenue generated by each genre.

Select g.genre_id, g.name, sum(i.total) as total_revenue from genre g join track t
on g.genre_id = t.genre_id join invoice_line il on t.track_id = il.track_id join
invoice i on il.invoice_id = i.invoice_id group by g.genre_id, g.name order by total_revenue desc;

--17 Find the most expensive track in the database.

Select track_id, name, unit_price from track order by unit_price desc limit 1;

--18 Show running cumulative revenue by invoice date.

Select invoice_date, total, sum(total) over(order by invoice_date) as running_total from invoice;

--19 Rank all customers based on total spending.

Select *, dense_rank() over(order by total_spending desc) as rank_number from (
Select c.customer_id, c.first_name, c.last_name, sum(i.total) as total_spending 
from customer c join invoice i on c.customer_id = i.customer_id group by c.customer_id, c.first_name, c.last_name);


--20. Find how much amount spent by each customer on artists? Write a query to return
--customer name, artist name and total spent


WITH best_selling_artist AS (
	SELECT artist.artist_id AS artist_id, artist.name AS artist_name, SUM(invoice_line.unit_price*invoice_line.quantity) AS total_sales
	FROM invoice_line
	JOIN track ON track.track_id = invoice_line.track_id
	JOIN album ON album.album_id = track.album_id
	JOIN artist ON artist.artist_id = album.artist_id
	GROUP BY 1
	ORDER BY 3 DESC
	LIMIT 1
)
SELECT c.customer_id, c.first_name, c.last_name, bsa.artist_name, SUM(il.unit_price*il.quantity) AS amount_spent
FROM invoice i
JOIN customer c ON c.customer_id = i.customer_id
JOIN invoice_line il ON il.invoice_id = i.invoice_id
JOIN track t ON t.track_id = il.track_id
JOIN album alb ON alb.album_id = t.album_id
JOIN best_selling_artist bsa ON bsa.artist_id = alb.artist_id
GROUP BY 1,2,3,4
ORDER BY 5 DESC;
